package es.upm.dit.isst.iocasasapi;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.springframework.web.util.JavaScriptUtils;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class RegistropuertapropietarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registropuertapropietario() {
    driver.get("http://localhost:8080/login");
    driver.manage().window().setSize(new Dimension(1296, 696));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("prop1@email.com");
    driver.findElement(By.id("password")).sendKeys("prop1");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Añadir")).click();
    driver.findElement(By.id("idPuerta")).click();
    driver.findElement(By.id("idPuerta")).sendKeys("123");
    driver.findElement(By.id("emailPropietario")).click();
    driver.findElement(By.id("emailPropietario")).sendKeys("prop1@email.com");
    driver.findElement(By.id("emailAdministrador")).sendKeys("admin1@email.com");
    driver.findElement(By.id("key")).sendKeys("123456");
    driver.findElement(By.id("ubicacion")).click();
    driver.findElement(By.id("ubicacion")).sendKeys("Madrid");
    driver.findElement(By.cssSelector(".btn-outline-primary")).click();
    driver.findElement(By.linkText("Editar")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(6)")).click();
    driver.findElement(By.id("ubicacion")).clear();
    driver.findElement(By.id("ubicacion")).sendKeys("Barcelona");
    driver.findElement(By.cssSelector(".btn-outline-primary")).click();
    driver.findElement(By.linkText("Eliminar")).click();
    driver.get("http://localhost:8086/login");
    driver.findElement(By.id("username")).sendKeys("prop1@email.com");
    driver.findElement(By.id("password")).sendKeys("prop1");
  }
}
