package es.upm.dit.isst.iocasasapi;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
public class RegistroReservaPropietarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty( "webdriver.chrome.driver", "/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registroReservaPropietario() {
    driver.get("http://localhost:8086/login");
    driver.manage().window().setSize(new Dimension(1296, 696));
    driver.findElement(By.id("username")).sendKeys("prop1@email.com");
    driver.findElement(By.id("password")).sendKeys("prop1");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.linkText("Añadir")).click();
    driver.findElement(By.id("idReserva")).click();
    driver.findElement(By.id("idReserva")).sendKeys("123");
    driver.findElement(By.id("idPuerta")).click();
    driver.findElement(By.id("idPuerta")).sendKeys("123456");
    driver.findElement(By.id("emailInquilino")).click();
    driver.findElement(By.id("emailInquilino")).sendKeys("inq1@email.com");
    driver.findElement(By.id("emailPropietario")).sendKeys("prop1@email.com");
    driver.findElement(By.id("emailAdministrador")).sendKeys("admin1@email.com");

    //MODIFICACIONES PARA QUE SE IMPORTE CORRECTAMENTE LAS FECHAS
    WebElement campoEntrada = driver.findElement(By.id("entrada"));
    js.executeScript("arguments[0].value='2023-05-09T12:00:00';", campoEntrada);
    WebElement campoSalida = driver.findElement(By.id("salida"));
    js.executeScript("arguments[0].value='2023-05-20T14:00:00';", campoSalida);
    // WebElement campoEntrada = driver.findElement(By.id("entrada"));
    // campoEntrada.sendKeys(Keys.chord(Keys.CONTROL, "a"), Keys.DELETE);
    // campoEntrada.sendKeys("10-05-2023 20:16");
    // driver.findElement(By.cssSelector(".form-group:nth-child(7) > .col-sm-6")).click();
    // WebElement campoSalida = driver.findElement(By.id("salida"));
    // campoSalida.sendKeys(Keys.chord(Keys.CONTROL, "a"), Keys.DELETE);
    // campoSalida.sendKeys("20-05-2023 20:16");
    driver.findElement(By.cssSelector(".form-group:nth-child(6) > .col-sm-6")).click();
    driver.findElement(By.cssSelector(".btn-outline-primary")).click();
    driver.findElement(By.linkText("Editar")).click();
    driver.findElement(By.id("salida")).click();
    WebDriverWait wait = new WebDriverWait(driver, 10); // Esperar hasta 10 segundos
    campoSalida = wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("salida")));
    js.executeScript("arguments[0].value='2023-06-01T17:00:00';", campoSalida);
    driver.findElement(By.cssSelector(".form-group:nth-child(7) > .col-sm-6")).click();
    driver.findElement(By.cssSelector(".btn-outline-primary")).click();
    driver.findElement(By.linkText("Eliminar")).click();
    driver.findElement(By.linkText("Log Out")).click();
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
